# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: foxy_grpc/pb2/strings.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'foxy_grpc/pb2/strings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x66oxy_grpc/pb2/strings.proto\x12\x12\x66oxy_grpc.protocol\"\x1e\n\rStringRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\r\"!\n\x0eStringResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t2h\n\rStringService\x12W\n\nGetStrings\x12!.foxy_grpc.protocol.StringRequest\x1a\".foxy_grpc.protocol.StringResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'foxy_grpc.pb2.strings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STRINGREQUEST']._serialized_start=51
  _globals['_STRINGREQUEST']._serialized_end=81
  _globals['_STRINGRESPONSE']._serialized_start=83
  _globals['_STRINGRESPONSE']._serialized_end=116
  _globals['_STRINGSERVICE']._serialized_start=118
  _globals['_STRINGSERVICE']._serialized_end=222
# @@protoc_insertion_point(module_scope)
