# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from foxy_grpc.pb2 import strings_pb2 as foxy__grpc_dot_pb2_dot_strings__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in foxy_grpc/pb2/strings_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StringServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStrings = channel.unary_stream(
                '/StringService/GetStrings',
                request_serializer=foxy__grpc_dot_pb2_dot_strings__pb2.StringRequest.SerializeToString,
                response_deserializer=foxy__grpc_dot_pb2_dot_strings__pb2.StringResponse.FromString,
                _registered_method=True)
        self.SayHi = channel.unary_unary(
                '/StringService/SayHi',
                request_serializer=foxy__grpc_dot_pb2_dot_strings__pb2.EmptyMessage.SerializeToString,
                response_deserializer=foxy__grpc_dot_pb2_dot_strings__pb2.EmptyMessage.FromString,
                _registered_method=True)
        self.Square = channel.unary_unary(
                '/StringService/Square',
                request_serializer=foxy__grpc_dot_pb2_dot_strings__pb2.Number.SerializeToString,
                response_deserializer=foxy__grpc_dot_pb2_dot_strings__pb2.Number.FromString,
                _registered_method=True)
        self.TellMe = channel.unary_unary(
                '/StringService/TellMe',
                request_serializer=foxy__grpc_dot_pb2_dot_strings__pb2.WhatAmI.SerializeToString,
                response_deserializer=foxy__grpc_dot_pb2_dot_strings__pb2.StringResponse.FromString,
                _registered_method=True)


class StringServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStrings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Square(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TellMe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStrings': grpc.unary_stream_rpc_method_handler(
                    servicer.GetStrings,
                    request_deserializer=foxy__grpc_dot_pb2_dot_strings__pb2.StringRequest.FromString,
                    response_serializer=foxy__grpc_dot_pb2_dot_strings__pb2.StringResponse.SerializeToString,
            ),
            'SayHi': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHi,
                    request_deserializer=foxy__grpc_dot_pb2_dot_strings__pb2.EmptyMessage.FromString,
                    response_serializer=foxy__grpc_dot_pb2_dot_strings__pb2.EmptyMessage.SerializeToString,
            ),
            'Square': grpc.unary_unary_rpc_method_handler(
                    servicer.Square,
                    request_deserializer=foxy__grpc_dot_pb2_dot_strings__pb2.Number.FromString,
                    response_serializer=foxy__grpc_dot_pb2_dot_strings__pb2.Number.SerializeToString,
            ),
            'TellMe': grpc.unary_unary_rpc_method_handler(
                    servicer.TellMe,
                    request_deserializer=foxy__grpc_dot_pb2_dot_strings__pb2.WhatAmI.FromString,
                    response_serializer=foxy__grpc_dot_pb2_dot_strings__pb2.StringResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('StringService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StringService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStrings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/StringService/GetStrings',
            foxy__grpc_dot_pb2_dot_strings__pb2.StringRequest.SerializeToString,
            foxy__grpc_dot_pb2_dot_strings__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SayHi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StringService/SayHi',
            foxy__grpc_dot_pb2_dot_strings__pb2.EmptyMessage.SerializeToString,
            foxy__grpc_dot_pb2_dot_strings__pb2.EmptyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Square(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StringService/Square',
            foxy__grpc_dot_pb2_dot_strings__pb2.Number.SerializeToString,
            foxy__grpc_dot_pb2_dot_strings__pb2.Number.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TellMe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StringService/TellMe',
            foxy__grpc_dot_pb2_dot_strings__pb2.WhatAmI.SerializeToString,
            foxy__grpc_dot_pb2_dot_strings__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
